### ISSUE TITLE
chromedriver unexpectedly exited

### ISSUE THREAD

**Issue by robroc** [21Buttons/pychromeless#1]
Hi there.

Thanks for creating this. It's just what I needed for a scraper I'm making.

When you deployed, did you ever run into these errors, even if it works locally with Docker:

~`selenium.common.exceptions.WebDriverException: Message: Service chromedriver unexpectedly exited. Status code was: 127`~

`selenium.common.exceptions.WebDriverException: Message: chrome not reachable`

or

`selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable may have wrong permissions.`

If so, how did you solve it?

I saw that you specified the path of the Chrome binary, but not the chromedriver. Does this need to be added as well?

**Comment by jairovadillo** [comment]
Hi! Thanks for contacting.

I've never run into this two errors... it's happening all the time? Can you share the full stack trace?

Also, the chromedriver should be in the PATH of the Lambda server so it's not needed to add its location anywhere. Can you share your lambda environment vars?

**Comment by robroc** [comment]
So after much gnashing of teeth, I solved it. It was a problem with incompatible versions of Selenium, chromedriver and headless-chrome. For some reason, the versions in your code didn't work on my Mac or my work PC.

These are the versions that worked for me, after much shuffling:

Selenium v.2.53.6
chromedriver v.2.37
serverless-chrome v.1.0.0-37
