### ISSUE TITLE
not able to install package chromedriver-installer

### ISSUE THREAD

**Issue by vmgustavo** [21Buttons/pychromeless#17]
Somehow it is not possible to install the package chromedriver-installer, I used pip search and found another named chromedriver_installer and the error is the same.

`Running setup.py install for chromedriver-installer: started
    Running setup.py install for chromedriver-installer: finished with status 'error'`

`    Exception: Unable to get latest chromedriver version from https://sites.google.com/a/chromium.org/chromedriver/downloads
`

`ERROR: Service 'lambda' failed to build: The command '/bin/sh -c pip3 install -r requirements.txt -t /var/task/lib' returned a non-zero code: 1
Makefile:23: recipe for target 'docker-run' failed
make: *** [docker-run] Error 1
`

**Comment by vmgustavo** [comment]
I changed the requirements to use the package chromedriver-install (instead of chromedriver-installer) and it seems to work out fine locally

**Comment by MHova** [comment]
I believe the root cause is this: https://github.com/authomatic/chromedriver_installer/issues/9

**Comment by MHova** [comment]
To add some more details to @vmgustavo's workaround, I changed `chromedriver-installer==0.0.6` to `chromedriver-install==1.0.3` in `requirements.txt`.

**Comment by jairovadillo** [comment]
Fixed here: https://github.com/21Buttons/pychromeless/commit/731b8cd6a3ccd9b04e71aacb4f3020e70d966ab4
