### ISSUE TITLE
Running pychromeless locally on Docker

### ISSUE THREAD

**Issue by robroc** [21Buttons/pychromeless#2]
Me again.

For those of us who are unfamiliar with Docker, can you please tell us how to test our app locally in it, or how to set up environment variables? I followed the Docker tutorial, but it's not clear. 

For example I keep getting these errors:

When I run:
`docker-compose run lambda`

I get:
`botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the GetObject operation: The AWS Access Key Id you provided does not exist in our records.`

Or when I run:
`docker run --rm -v "$PWD":/var/task lambci/lambda:python3.6 lambda_function.lambda_handler`

I get:
`Unable to import module 'lambda_function': No module named 'selenium'`

Thanks for any additional help you can spare.

**Comment by jairovadillo** [comment]
Hey! I've updated the README because it was WRONG (sorry). You just need to do:

`make fetch-dependencies`
`make docker-run`

Aaand you're good to go!

**Comment by robroc** [comment]
Thank you for this. Recently I did:

`make fetch-dependencies`
`make docker-build`
`make docker-run`

And it worked. Is the docker-build step unnecessary?
