### ISSUE TITLE
Problem with running JavaScript and HTML DOM rendering...?

### ISSUE THREAD

**Issue by donatasno** [21Buttons/pychromeless#21]
## Description
First of all, I wanted to thank you guys for sharing this great repo - the deployed example function works as expected. However, when I use basically the same code, I seem to encounter issues with HTML DOM rendering. Well, at least to my understanding. Could this be related to the driver options you proposed? The following function works fine with a non-headless desktop Chrome driver but fails when deployed and using the headless mode.

## Steps to reproduce

- Update the lambda function:
```python
def lambda_handler(*args, **kwargs):
    driver = WebDriverWrapper()

    url = r'https://www.idealo.de/preisvergleich/OffersOfProduct/3214257_-cobra-paket-3-tlg-00-20-09-v02-knipex.html'
    driver.get_url(url)

    driver.click('//button[@class="productOffers-listLoadMore button-ghost button-ghost--blue"]')

    print("--------------------------")
    print("Success!")
    print("--------------------------")

    driver.close()
```
- Deploy or run the function inside a docker container.

## Observed result
Once I deploy and run the function above I get the infamous ```selenium.common.exceptions.NoSuchElementException``` error:

```python
Message: no such element: Unable to locate element: {"method":"xpath","selector":"//button[@class="productOffers-listLoadMore button-ghost button-ghost--blue"]"}
  (Session info: headless chrome=62.0.3202.94)
  (Driver info: chromedriver=2.32.498513 (2c63aa53b2c658de596ed550eb5267ec5967b351),platform=Linux 4.14.138-99.102.amzn2.x86_64 x86_64)
: NoSuchElementException
Traceback (most recent call last):
  File "/var/task/src/lambda_function.py", line 13, in lambda_handler
    driver.click('//button[@class="productOffers-listLoadMore button-ghost button-ghost--blue"]')
  File "/var/task/src/webdriver_wrapper.py", line 68, in click
    elem_click = self._driver.find_element_by_xpath(xpath)
  File "/var/task/lib/selenium/webdriver/remote/webdriver.py", line 290, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/var/task/lib/selenium/webdriver/remote/webdriver.py", line 744, in find_element
    {'using': by, 'value': value})['value']
  File "/var/task/lib/selenium/webdriver/remote/webdriver.py", line 233, in execute
    self.error_handler.check_response(response)
  File "/var/task/lib/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//button[@class="productOffers-listLoadMore button-ghost button-ghost--blue"]"}
  (Session info: headless chrome=62.0.3202.94)
  (Driver info: chromedriver=2.32.498513 (2c63aa53b2c658de596ed550eb5267ec5967b351),platform=Linux 4.14.138-99.102.amzn2.x86_64 x86_64)
```
## Expected result
I expect the "Load more" button element to be found in order to be clicked.

## Additional environment details
- Lambda runtime ``Python 3.6``
- xPath retrieved using Google Chrome (on Ubuntu 18.04 desktop) ``Version 79.0.3945.130 (Official Build) (64-bit)``

## Things I have tried so far:
- install older Google Chrome browser (``62.0.3202.75``) and check if the xPath is different somehow after the rendering of the HTML DOM;
- give the driver more time to run the Java Script by setting ``time.sleep(120)``;
- try passing absolute or relative xPath to `` driver.click()`` method;
- inspect the page source by adding the following method to the ``WebDriverWrapper`` class:
```python
    def get_source_html(self):
        return self._driver.page_source
```
Interestingly, this ``get_source_html()``method returned unrendered content for both the original and the modified function. Despite this the headless Chrome was still able to find the elements by xPath in the original function, but fail to do so in the modified version. I think this point is what bugs me the most at the moment - the desktop version of the chrome driver returns a nicely rendered HTML once ``driver.page_source`` is used and I can easily verify that the button is present on the page. But as the same method on headless version returns a bunch of Java Script (as far as I am aware this can happen with HTML DOM), I cannot check and see what the headless Chrome driver is "looking at" and what kind of HTML it is working with. I read the available options list for the driver, but I could not find an explicit "run Java Script" method (nor there should be one, this is what the driver should be doing automatically as far as I'm concerned...) 

Any ideas on how to proceed here are very welcome.

**Comment by donatasno** [comment]
Well, I tried one more thing. I have added another method to the ``WebDriverWrapper`` class so me and my headless friend could "share the view".

```python
    def take_screenshot_binary(self):
        return self._driver.get_screenshot_as_png()
```

Then I added the following to the main function so I could dump the binary object to the S3 bucket:
```python
s3_client = boto3.client('s3')
s3_client.put_object(Bucket='some-bucket-name',
                         Key=f'main_page_idealo.png',
                         Body=driver.take_screenshot_binary()
                         )
```

I was not too happy with the result:

![main_page_idealo](https://user-images.githubusercontent.com/45568443/74057921-925f0900-49ed-11ea-8323-52a1feb33432.png)


 It seems that the page is set up in such a way that blocks the headless driver from doing its thing. It's strange that the desktop version of the driver does not get blocked. That mislead me into believing the page is possible to scrape.

I am closing the issue, apologies for raising this in the first place, should have investigated this a bit deeper myself.

**Comment by christophertull** [comment]
Weird! I had never considered that option before, but I suppose it makes sense to allow humans but not bots, and I guess a headless browser would be a pretty good indication of a bot...

Sorry to hear it isn't working for you!

Also, clever trick with the screenshots! That alone seems like an approach worth sharing.
