### ISSUE TITLE
ElementNotVisibleException from clean run of repo

### ISSUE THREAD

**Issue by jbjbjb1** [21Buttons/pychromeless#23]
I have cloned the repo and run `make fetch-dependencies` as written. When I go to run `make docker-run` as written in the readme I get this error:

{"errorType":"ElementNotVisibleException","errorMessage":"Message: element not visible\n  (Session info: headless chrome=62.0.3202.94)\n  (Driver info: chromedriver=2.32.498513 (2c63aa53b2c658de596ed550eb5267ec5967b351),platform=Linux 5.4.0-52-generic x86_64)\n","stackTrace":["  File \"/var/task/src/lambda_function.py\", line 15, in lambda_handler\n    button.send_keys(Keys.TAB)\n","  File \"/var/task/lib/selenium/webdriver/remote/webelement.py\", line 322, in send_keys\n    self._execute(Command.SEND_KEYS_TO_ELEMENT, {'value': keys_to_typing(value)})\n","  File \"/var/task/lib/selenium/webdriver/remote/webelement.py\", line 457, in _execute\n    return self._parent.execute(command, params)\n","  File \"/var/task/lib/selenium/webdriver/remote/webdriver.py\", line 233, in execute\n    self.error_handler.check_response(response)\n","  File \"/var/task/lib/selenium/webdriver/remote/errorhandler.py\", line 194, in check_response\n    raise exception_class(message, screen, stacktrace)\n"]}
make: *** [Makefile:35: docker-run] Error 1

**Comment by lamarrh** [comment]
ran into this issue today and it was fixed by changing the url from google.es to google.com

**Comment by jairovadillo** [comment]
I've changed the example since depending of the country may lead to errors, for example, here in Spain it's not working because of the "consent" banner that google shows. The new one is way more simpler but at least works all the time :)
