### ISSUE TITLE
Error Deploying on AWS Lamnda

### ISSUE THREAD

**Issue by samuel2629** [21Buttons/pychromeless#29]
When i deploy on aws lambda and test it i get this error :

`
{ "errorMessage": "Unable to import module 'lambda_function': No module named 'lambda_function'", "errorType": "Runtime.ImportModuleError" }`

Please let me know what i'm doing wrong. Thank you.

**Comment by marcelcastrobr** [comment]
You forgot to include environment variables in your lambda. 
They are: 
PYTHONPATH=/var/task/src:/var/task/lib
PATH=/var/task/bin

After that it should work.

**Comment by samuel2629** [comment]
Yes i figured it that out, i forgot to answer my own question. Thank you though !!
