### ISSUE TITLE
WebDriverWrapper Subclass

### ISSUE THREAD

**Issue by rneu31** [21Buttons/pychromeless#6]
Is it possible to have WebDriverWrapper subclass webdriver.Chrome so the methods of webdriver.Chrome are available?

Tried doing so myself and can't quite get it right for whatever reason.

**Comment by jairovadillo** [comment]
Hi! The main idea of _ WebDriverWrapper_ as is name indicates is to wrap/isolate the webdriver from the outside, anyway you can create your own _ WebDriverWrapper_ with your custom methods, even you could change the [self._driver here](https://github.com/21Buttons/pychromeless/blob/49cd768b808bf5c909a9749f025033c4f6779db4/src/webdriver_wrapper.py#L44) by `self.driver` and make this object public and access via `WebDriverWrapper().driver`

Hope this helps!
