### ISSUE TITLE
Boto3

### ISSUE THREAD

**Issue by rneu31** [21Buttons/pychromeless#7]
Overwriting PYTHONPATH loses LAMBDA_RUNTIME_DIR (where packages such as boto3 are).

Any hints on how to get around this?

Thanks!

**Comment by rneu31** [comment]
I solved it by including `/var/runtime` to the PYTHONPATH sent to the Lambda function (Terraform in this example).
```
  environment = {
    variables = {
      "PYTHONPATH" = "/var/runtime:/var/task/src:/var/task/lib",
      "PATH" = "/var/task/bin"
    }
  }
````

**Comment by jairovadillo** [comment]
Great! Could you please create a PR to add the terraform part? 🙏

**Comment by christophertull** [comment]
Would love to see a basic terraform script added here. Might be able to add myself if @rneu31 doesn't get around to it.
