### ISSUE TITLE
Question: geolocation

### ISSUE THREAD

**Issue by rneu31** [21Buttons/pychromeless#8]
Have you, in your masterful experience, used html5 geolocation?

I'm navigating to `https://html5demos.com/geo` and taking a screenshot and it displays failed.

I did some digging and tried to allow geolocation access to that specific site, which did not work;

```
        prefs = {
            'profile.content_settings.geolocation': {
                "https://html5demos.com:443,https://html5demos.com:443": {
                    "last_modified": "13176769719334225",
                    "setting": 1
                }
            },
        }
        chrome_options.add_experimental_option("prefs", prefs)
```

I've also seen various stackoverflow articles mentioning the settings
```
'profile.managed_default_content_settings.geolocation': 1,
'profile.default_content_setting_values.geolocation': 1,
'profile.default_content_settings.geolocation': 1,
```

Any insight is appreciated. I'll close the issue shortly regardless -- since it isn't a real issue.

Thanks for your time.

**Comment by jairovadillo** [comment]
But trying to get geolocalization from Lambda will always give you the lambda localization right? Like if you are in eu-west will tell you "Ireland" always.

**Comment by rneu31** [comment]
For my application that would be sufficient. But I'm also fairly confident if the geolocation was available, that stubbing it out via an execute_script would be possible.

**Comment by jairovadillo** [comment]
Closing this since it's a little bit out of scope 🙏
